In [1]:
import pandas as pd
import numpy as np
import json
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.decomposition import PCA


In [2]:
df = pd.read_csv('df_df+log.csv')

In [3]:
df.head();

In [13]:
df.shape

(8334, 30)

In [10]:
X_c = df[['log_time_allowed', 'log_goal']]

In [14]:
X_c.shape

(8334, 2)

In [11]:
# from sklearn.preprocessing import StandardScaler
# X_c_s = pd.DataFrame(data = StandardScaler().fit_transform(X_c), columns = ['log_time_allowed', 'log_goal']).head()

In [16]:
X_d = pd.get_dummies(df[['cat_slug', 'staff_pick', 'country', 'loc_state', 'cat_name']], drop_first=True, prefix_sep='_')

In [17]:
X = pd.concat([X_c,X_d],1)
X;

In [18]:
X.dropna(0,inplace=True)

In [19]:
X.shape

(8334, 675)

In [20]:
y = pd.get_dummies(df[['state']], drop_first=True)
y;

In [114]:
pca = PCA(n_components=4)
principalComponents = pca.fit_transform(X)

In [102]:
pca.components_;

In [103]:
pca.mean_;

In [104]:
pca.explained_variance_ratio_

array([0.4420274 , 0.07802487, 0.05099952, 0.01601716, 0.01589592,
       0.01061357, 0.00827132, 0.00789383, 0.00767629, 0.00720554,
       0.00608779, 0.00591709, 0.0054819 , 0.00521564, 0.00455749,
       0.00450097, 0.00446802, 0.00440973, 0.00434367, 0.00430328])

In [105]:
np.cumsum(pca.explained_variance_ratio_)

array([0.4420274 , 0.52005228, 0.5710518 , 0.58706896, 0.60296488,
       0.61357845, 0.62184977, 0.62974359, 0.63741988, 0.64462542,
       0.6507132 , 0.6566303 , 0.66211219, 0.66732784, 0.67188533,
       0.6763863 , 0.68085431, 0.68526404, 0.68960771, 0.69391098])

In [100]:
df_pca = pd.DataFrame(data = principalComponents
             , columns = ['PC1', 'PC2','PC3','PC4'])
result_df = pd.concat([df_pca, y], axis = 1)
result_df.head(5)

PC1       PC2       PC3       PC4  state_successful
0 -0.616311  1.901775 -0.141234 -0.126610                 1
1 -0.084882  0.079091 -0.412296  0.791566                 0
2  2.658113 -0.027651 -0.487770  0.834370                 0
3  1.723089  0.627544 -0.353859 -0.421949                 1
4  1.494201 -0.375729 -0.422812 -0.409234                 1

In [108]:
X_1 = result_df[['PC1','PC2','PC3','PC4']]

In [109]:
y_1 = result_df[['state_successful']]

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X_1, y_1, test_size = 0.3, shuffle=True)

In [111]:
from sklearn import svm

clf = svm.SVC(kernel='linear')
clf.fit(X_1, y_1)

/Users/flatironschool/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [112]:
clf.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=uint8)

In [113]:
accuracy_score(y_test,clf.predict(X_test))

0.6345461815273891